### ISSUE TITLE
Uncaught DOMException: Failed to execute 'getExtentOfChar' on 'SVGTextContentElement'

### ISSUE THREAD

**Issue by zxxshaycormac** [yWorks/svg2pdf.js#58]
Hi,

I have the following error in my browser console:
```
Uncaught DOMException: Failed to execute 'getExtentOfChar' on 'SVGTextContentElement': The charnum provided (16) is greater than or equal to the maximum bound (16).
    at t.calculateInitialPosition (webpack-internal:///./node_modules/poplar-annotation/dist/index.js:26:69370)
    at t.render (webpack-internal:///./node_modules/poplar-annotation/dist/index.js:16:156850)
    at t.eval [as _next] (webpack-internal:///./node_modules/poplar-annotation/dist/index.js:16:155676)
    at t.__tryOrUnsub (webpack-internal:///./node_modules/poplar-annotation/dist/index.js:16:3228)
    at t.next (webpack-internal:///./node_modules/poplar-annotation/dist/index.js:16:2419)
    at r._next (webpack-internal:///./node_modules/poplar-annotation/dist/index.js:16:1471)
    at r.next (webpack-internal:///./node_modules/poplar-annotation/dist/index.js:16:1142)
    at i.eval (webpack-internal:///./node_modules/poplar-annotation/dist/index.js:16:40523)
    at i.emit (webpack-internal:///./node_modules/poplar-annotation/dist/index.js:16:47422)
    at t.set [as json] (webpack-internal:///./node_modules/poplar-annotation/dist/index.js:16:150073)
```

Well I know this issue looks like:

[https://github.com/yWorks/svg2pdf.js/issues/16](https://github.com/yWorks/svg2pdf.js/issues/16)

But I'm using v1.3.0,and it does appear.

Thanks,

Shay

**Comment by yGuy** [comment]
Please provide at least the SVG that triggered this exeption.
